### ISSUE TITLE
Broken download link for gemoc studio

### ISSUE THREAD

**Issue by AlexandreRio** [gemoc/gemoc.github.io#1]
Download links on the following page do not work (404 error) http://gemoc.org/download.html
Example of link: http://gemoc.org/pub/studio/gemoc_studio_2017_02_27/gemoc_studio-linux.gtk.x86_64.zip

**Comment by dvojtise** [comment]
link to the studio is now ok and redirect to gemoc.irisa.fr (real host), 
direct link to a special version of the update site is ok
remains an issue with update permalinks because we don't really want ot change them as they are predefined in existing eclipse installations.

**Comment by AlexandreRio** [comment]
Ok that's fine with me (and the opened issue).
Thanks,
I'm closing the issue
