### ISSUE TITLE
Remove error HTTPS access

### ISSUE THREAD

**Issue by ebousse** [gemoc/gemoc.github.io#26]
When accessing gemoc.org in HTTPS, there is a certificate error. Would be good to fix it.

Also an automatic redirect from _http_ to _https_ would be great, as it is quite standard nowadays.

**Comment by combemale** [comment]
It seems that we can not use HTTPS on github pages when a custom domain is configured. Message: "Enforce HTTPS — Unavailable for your site because you have a custom domain configured (gemoc.org)". Any idea?

**Comment by ebousse** [comment]
OK, I investigated a bit, and it's actually impossible to have proper HTTPS support with github pages with a custom domain. The issue is still opened here: https://github.com/isaacs/github/issues/156

So unfortunately, the only solution to solve this would be to move the website to our own webserver. Too bad :(

**Comment by dvojtise** [comment]
does this can help fix this issue https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ ?

**Comment by dvojtise** [comment]
The referenced issue is now indicated as closed, it also indicates some action could be done to fix that
