### ISSUE TITLE
Logo on the AS 2011 webpage

### ISSUE THREAD

**Issue by combemale** [gemoc/gemoc.github.io#3]
http://gemoc.org/projects/as2011.html

**Comment by manuelleduc** [comment]
cf http://gemoc.org/as2011/

**Comment by combemale** [comment]
ok, I just corrected the url in the header... 

do you know why as2011 is using html and mbsar md?

**Comment by manuelleduc** [comment]
I renamed it by accident. It does not makes any difference since every non-markdown part of the grammar is view as html by mardown's parser.

**Comment by combemale** [comment]
can you make them uniform? 

thx
