### ISSUE TITLE
broken links to download versions

### ISSUE THREAD

**Issue by dvojtise** [gemoc/gemoc.github.io#4]
I don't know what have changed since the last time I' checked it but currently many links  in the http://gemoc.org/download.html page are broken (ex: http://studio_releases/eclipse_package/updatesite/2017/02/27/v2.3.0.html should point to http://gemoc.org/studio_releases/eclipse_package/updatesite/2017/02/27/v2.3.0.html; the virtual box image link is also wrong)

**Comment by combemale** [comment]
you can check the history. btw: did you correct them?
