### ISSUE TITLE
Permalink to latest stable version doesn't link to the latest version

### ISSUE THREAD

**Issue by lmouline** [gemoc/gemoc.github.io#53]
while adding `http://gemoc.org/updatesite/studio` to the update site, I got an older version of the Studio.

Here the list of pakcages I get (filtered to show only the Gemoc ones)
![Screenshot 2020-01-17 at 14 38 10](https://user-images.githubusercontent.com/2489384/72616349-051d1d00-3937-11ea-9882-efd5c493735c.png)

**Comment by dvojtise** [comment]
Thanks for reporting this issue

I changed the permalink in the [download page ](http://gemoc.org/download.html#update-site)to https://download.eclipse.org/gemoc/updates/latest_stable

You should now get the latest from milestones and releases
